apiVersion: apps/v1
kind: Deployment
metadata:
  name: makaan
  labels:
    app: house
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: house
  template:
    metadata:
      labels:
        app: house
    spec:
      containers:
      - name: hose-renting-container
        image: bhanuprakashnrb/nginx:v.2.0  # Replace with your Docker Hub image path
        imagePullPolicy: Always  # Always attempt to pull the image
        ports:
        - containerPort: 80  # Replace with the port your application listens on
        readinessProbe:
          httpGet:
            path: /index.html  # Replace with your application's readiness endpoint
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /index.html # Replace with your application's liveness endpoint
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /index.html  # Replace with your application's startup endpoint
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
      imagePullSecrets:
      - name: regcred # Replace with the name of your Docker Hub secret
