apiVersion: v1
kind: Service
metadata:
  name: makaan-service
spec:
  selector:
    app: house
  ports:
    - protocol: TCP
      port: 80  # Port on the service
      targetPort: 80  # Port on the pods
  type: LoadBalancer  # Use "LoadBalancer" to expose the service externally
